# Reproducible Research: Peer Assessment 1


## Loading and preprocessing the data
```{r setoptions, echo=TRUE}
library(Defaults)

setDefaults('as.Date.character', format = '%Y-%m-%d')

activity <- read.csv(file='activity.csv', header=TRUE, 
                     colClasses = c("numeric","Date","numeric"))
activity.complete_cases <- activity[complete.cases(activity),]
```

## What is mean total number of steps taken per day?
```{r}
library(lattice)
library(plyr)

activity.complete_cases.daily <- ddply(activity.complete_cases, .(date), 
                        summarize, steps=sum(steps))
histogram(activity.complete_cases.daily$steps, breaks=15)
```

### Mean and median daily steps (complete cases)
```{r}
mean(activity.complete_cases.daily$steps)
median(activity.complete_cases.daily$steps)
```

## What is the average daily activity pattern?
```{r}
activity.complete_cases.daily_average <- ddply(activity.complete_cases, .(interval), summarize, steps=mean(steps))
xyplot(steps ~ interval , data=activity.complete_cases.daily_average, type="l")
```

## Imputing missing values
```{r}
activity.missing <- activity[is.na(activity$steps),]
activity.missing$steps <- activity.complete_cases.daily_average$steps[
  match(activity.missing$interval, 
        activity.complete_cases.daily_average$interval)]

activity$steps <- ifelse(is.na(activity$steps), activity.missing$steps, activity$steps)

activity.daily <- ddply(activity, .(date), summarize, steps=sum(steps))

histogram(activity.daily$steps, breaks=15)
```

### Mean and median daily steps (imputed)
```{r}
mean(activity.daily$steps)
median(activity.daily$steps)
```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
activity$day <- ifelse(weekdays(activity$date) %in% c("Saturday", "Sunday"), "weekend", "weekday")
activity.daytype <- ddply(activity, .(day, interval), summarise, steps=mean(steps))
xyplot(steps ~ interval | day, data=activity.daytype, type="l", layout=c(1, 2))
```

